### ISSUE TITLE
delite/FormWidget widget user cannot customise aria attributes using markup

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/delite#193]
delite/FormWidget doesn't allow the widget root node to be focusable. As a consequence, it sets the aria attributes of the widget on the focusable child(ren) node(s).

One drawback of the current implementation is that if a user defines a custom aria attribute using markup, as in:

```
<my-form-widget aria-labelledby="someId"></my-form-widget>
```

The `aria-labelledby` property is set on the root node, instead of being set on the focusable child(ren) nodes.

**Comment by wkeese** [comment]
FWIW, this change seems less important than before.  I reverted the change and then tested StarRating against JAWS 17, and JAWS reads the aria label even though it's on the root node rather than the focus node.  As @sbrunot wrote above:

> JAWS read it as "aria-label value frame"

I know that I wrote that it doesn't work above, and @sbrunot confirmed it, saying:

> I confirm that the aria-labelledby attribute is ignored by JAWS when a star rating widget has the focus.

But now I can't reproduce that.   I even tried against JAWS 15 (in addition to JAWS 17), albeit it was against Firefox 51 not Firefox 14.

The one case I found where it helps is VoiceOver.  VoiceOver will announce an aria-labelledby attribute if it's on the `<input>` but not if it's on a `<span>` wrapping the `<input>`.

As a side note the nested `<div role=slider>` inside the `<d-star-rating>` widget seems useless; I think those two elements could be combined.
