### ISSUE TITLE
Store: rename to something less confusing

### ISSUE THREAD

**Issue by wkeese** [ibm-js/delite#308]
See ibm-js/deliteful#334.

**Comment by cjolif** [comment]
With the work @harbalk is doing, I think deliteful/Store will disappear because it will be easier to create a "source" of data in markup without instantiating a dstore.  So that will be one less confusion (see: 902b920cf747fcbbb91694aa94f2800b3dd064ef).

With that in mind, I think I'm personally fine keep delite/Store naming as is. However I guess the ` store` property of delite/Store should be renamed as it can take either a store or an array. Maybe `source` ?

**Comment by AdrianVasiliu** [comment]
>  Maybe `source` ?

Or maybe  `data`?

**Comment by harbalk** [comment]
I think ```source``` is more suitable because the data used can be different from the source (after a query condition for example).
Maybe ```dataSource``` to be clearer ? But it is a bit long.

**Comment by cjolif** [comment]
@wkeese any feedback? how would you like the "store" property to be renamed following @harbalk work?

**Comment by wkeese** [comment]
`source` seems good to me.

But I still want to change the name of the delite/Store class, because then "store" can mean two things (either delite/Store or dstore).

**Comment by wkeese** [comment]
deliteful/Store was removed in ibm-js/deliteful@11a4c8d33dd91d816d4b10beef17ecc57dd0fb08 and delite/Store's `store` property was renamed to `source` in 56672f8fd794771cf95c0229aee15e206d530394.

I'd still like to rename the delite/Store class, since it's not a dstore Store, but rather an interface to either dstore/Store or decor/ObservableArray.

**Comment by wkeese** [comment]
Closing this just because we're unlikely to ever do it.
