### ISSUE TITLE
CustomElement: attributeChangedCallback implementation

### ISSUE THREAD

**Issue by cjolif** [ibm-js/delite#343]
CustomElement spec provides a attributeChangedCallback method. Ideally we should provide it as well provided we can implement it on all our support browsers.

**Comment by wkeese** [comment]
Although it's easy to track attribute changes made through `Widget#setAttribute()`, it's hard to track changes made via an attribute's shadow property, for example:

```
myWidget.title = "hello world";
```

instead of

```
myWidget.setAttribute("title", "hello world");
```

It's easy on some platforms:

* chrome provides built-in attributeChangedCallback() method
* modern browsers provide MutationObserver / WebkitMutationObserver
* IE provides "DOMAttrModified" event

However, on Android < 4.4 the only "non-invasive" option is to listen to the DOMSubTreeModified event, but the performance is prohibitive and also, it only gives notification when attributes are added/deleted, not when their value is changed.

So, that leaves our old approach of using custom setters, with a fallback on Chrome to use MutationObserver.   We would need to set up custom setters for every property that shadows a DOM attribute (title, alt, etc.), and the custom setters would all do the same thing: call setAttribute().

I tried this and it worked on FF and Android 4.4.  The tests on Android 4.2 aren't running for me at all at the moment.

So, even if I can get this to work cross browser, this approach makes the solution pretty complicated, with dubious value (aside from marketing).   A subclass can already override setAttribute(), and if a subclass needs to monitor changes to a certain property, we can handle it like we currently handle `dir` and `tabIndex`.  So I'd like to close this ticket as wontfix (at least for now).

@cjolif, sound ok?

**Comment by cjolif** [comment]
Yes. I think this is reasonable to say (and document clearly) we are not supporting this for now. We might want to revisit this when/if our browser support list is shrinking.

**Comment by wkeese** [comment]
OK, I updated the doc, so closing this at least for now.
