### ISSUE TITLE
popup: incorrect height in some cases with "center" orientation

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/delite#347]
In some cases, at least with  https://github.com/ibm-js/delite/blob/master/tests/functional/popup.html, a delite/popup with `orient: ["center"]` has a wrong height every second time it opens. 

How to reproduce:
1. Load https://github.com/ibm-js/delite/blob/master/tests/functional/popup.html in any browser (reproduced on Chrome, FF, IE  / Win7, and Safari iOS 8.1.2).
2. Click/touch the "show giant centered dialog" button.
=> The popup appears with correct size (so far so good):
![image](https://cloud.githubusercontent.com/assets/1583981/5488114/b8471448-86b9-11e4-9dce-74fea36c08a3.png)
3. Reopen the same popup (either clicking/touching again the button, or first closing by touching/clicking outside then opening again).
=> Now the popup has a wrong height and the content (which here has overflow-y: auto) appears in scrolled position:
![image](https://cloud.githubusercontent.com/assets/1583981/5488124/cd5dfa04-86b9-11e4-8f5e-9da54992e1a8.png)
4. Successively reopening the popup alternates between the correct and the wrong height.

Remarks:
- The debugger shows that the height of the popup alternates between a size in px (as calculated by the popup to adjust to the available space) - when the height is correct - and "height: auto" - when the height is incorrect. That is, it looks as if the size computation fails when the initial size is a hardcoded one (the one set the previous time the popup was open).
- I'm not sure if the issue is in the test, or in the library code.
- This problem does not seem to affect widgets subclassing HasDropDown, or at least I could not reproduce with HasDropDown in centered position.

**Comment by lbod** [comment]
So I think I've found the issue but wanted feedback first before creating a PR. 
Here's the commit https://github.com/lbod/delite/commit/13b14b6d02c33ec13b548f0eaba34afbf68bfaf8

I've ran a full saucelabs suite and all passed:

It'll only occur when it's a centered popup and only when the popup height is greater than the viewport height. The first time it's opened, the wrapper & popup height will be set to a fixed value, on a subsequent open, the comparison fails due to not using `Math.floor` to compare the viewport height. Also, it should check whether the `_naturalHeight` is greater __or equal__ to the viewport height.

I don't think there's a functional test for `"show giant centered dialog"` and certainly not for this particular problem. 
I presume I should add this to the functional test? Will it just be a case of testing if the `wrapper.offSetHeight` is less or equal to the viewport height?
Also, it'll need to do a subsequent open to check again?

I also spotted another bug with large popups & not sure if it's been raised yet. If it hasn't I'll raise it.
If you open a large popup (like this one) and then resize the browser you'll eventually see a similar problem. This happens before and after my commit

**Comment by wkeese** [comment]
Sounds like there are a bunch of issues, and also (like you said) that we need more tests.

> the comparison fails due to not using Math.floor to compare the viewport height and the height of the popup is then set to auto (which should only happen if the popup height is less than the viewport height). 
Also, the comparison should check whether the _naturalHeight is greater or equal

I don't understand why you need Math.floor() or why it matters if it's greater vs. greater-or-equal.  That code you linked tries to limit the dialog to 90% of the size of the viewport, so I don't understand why it would matter if it were off by a pixel?

> I also spotted another bug with large popups & not sure if it's been raised yet. If it hasn't I'll raise it.

I don't think it's been raised.

>  I also see a problem with the "show tall drop down" popup on subsequent opens. Looks like another issue. ... I guess this should be a separate issue rather than bundled with this fix?

I guess so; I don't have a strong opinion either way.

**Comment by lbod** [comment]
> I don't understand why you need Math.floor() or why it matters if it's greater vs. greater-or-equal. That code you linked tries to limit the dialog to 90% of the size of the viewport, so I don't understand why it would matter if it were off by a pixel

@wkeese I realise that's why it limits it to 90% (also shouldn't that be configurable rather than hardcoded?). The issue is the ternary test and expression are not equivalent.

What happens is this: 

1. Stick a breakpoint at the ternary comparison.
2. Launch the popup for the first time. 
3. In my case `args._naturalHeight = 2021`, `viewport.h * 0.9 = 414.90000000000003`. Therefore `wrapper.style.height` is set to `Math.floor(viewport.h * 0.9)` i.e. 414px;
4. Close the popup then relaunch it
5. In my case `args._naturalHeight = 414`, `viewport.h * 0.9 = 414.90000000000003`. Therefore `wrapper.style.height` is set to `auto`

`wrapper.style.height` should only ever be set to `auto` when the `_naturalHeight` is greater than 90% of the viewport height but the height is being set to a floored value, whereas the comparison isn't comparing against the floored value.

> or why it matters if it's greater vs. greater-or-equal. 

Again because `wrapper.style.height` should only ever be set to `auto` when the `_naturalHeight` is __greater__ than 90% of the viewport height. Conversely, `Math.floor(viewport.h * 0.9)` must be __less__ than `args._naturalHeight`; if they are equal then `wrapper.style.height` will again be set to `auto`.

The same comparison issues also apply to the width.

I'll look at the other problems, raise issues and bundle with the same PR. I'll need to work on improving the tests for these so it'll take me a week, unless you want to take this fix now?

**Comment by wkeese** [comment]
OK, so you are trying to get the numbers to match exactly.  Probably it's better to just remove the height that popup.js set the first time.    Actually hide() already has code for that, but for some reason it's apparently not working.   Anyway, we shouldn't pretend that the popup's natural (aka unconstrained) height is 414 when really it's 2021.

One thing to think about is if the mobile user switches from landscape to portrait, or if a desktop user expanded/reduced the size of the viewport.   In that viewport.h will be very different than 414, even with the Math.floor().

**Comment by lbod** [comment]
> OK, so you are trying to get the numbers to match exactly. Probably it's better to just remove the height that popup.js set the first time. 

No I'm not trying to match up numbers exactly, I'm only fixing the current code to work correctly. It seems you're thinking a more fundamental change is needed?  

> Actually hide() already has code for that, but for some reason it's apparently not working. Anyway, we shouldn't pretend that the popup's natural (aka unconstrained) height is 414 when really it's 2021.

Sorry, not sure what you're saying here. The current code uses the widget `offSetHeight` to set the wrapper `_naturalHeight` i.e. https://github.com/ibm-js/delite/blob/master/popup.js#L397
The change I made to this code is minor; that code is trying to work out the difference between the `natural` height i.e. `widget.offsetHeight` compared to the viewport height. 
If you think this is a more fundamental change it'll need more discussion.  

> One thing to think about is if the mobile user switches from landscape to portrait, or if a desktop user expanded/reduced the size of the viewport. In that viewport.h will be very different than 414, even with the Math.floor().

That should be handled by `resize` shouldn't it? The first other issue I mentioned seemed to point to `Viewport.on("resize", this._repositionAll.bind(this));` which I've not had time to look at yet. Like I said, I'll raise separate issues for these because it'll just pollute the comments even more than I've done.

**Comment by lbod** [comment]
> @wkeese I realise that's why it limits it to 90% (also shouldn't that be configurable rather than hardcoded?).

We should address this too e.g. like https://github.com/dojo/dijit/blob/master/Dialog.js#L100 `maxRatio`

**Comment by wkeese** [comment]
Lee, in your example step 5 says args._naturalHeight = 414.   That number is completely off.   It should be 2021.  Is it clear what I meant by the "natural height" of the popup?  I'm talking about the height that it would be in an infinitely sized viewport.

About switching from portrait to landscape, I was talking about switching when the drop down is hidden, i.e. during your step 4.

**Comment by lbod** [comment]
> Lee, in your example step 5 says args._naturalHeight = 414. That number is completely off. It should be 2021

Yeh try it out, simple to set a breakpoint there and see the behaviour. The height of the wrapper is set to  414 on the first open.

> Is it clear what I meant by the "natural height" of the popup? I'm talking about the height that it would be in an infinitely sized viewport.

Yep. That's what the `offSetHeight` is meant for. 

Like I say, stick a breakpoint there and launch popup > close popup > launch popup & you'll see the same.
It goes back and forth from a fixed px size to auto

**Comment by wkeese** [comment]
Yes, the code needs to be fixed.   Now, after your fix, on the second iteration, is args._naturalHeight 2021?

**Comment by lbod** [comment]
I see what you're saying but no, `args._naturalHeight` will be set to the resized height after the first launch so will not be set to the same initial auto height value, instead it'll be set to the previously set height (`offSetHeight`) when the popup is launched again. From how the code is currently designed that seems correct.

**Comment by wkeese** [comment]
>  args._naturalHeight will be set to the resized height after the first launch

OK, so I don't think your fix is addressing the root issue.   Every time that block of code runs, it needs to compare the viewport's current height to the height the popup *would have been if it hadn't been shrunk by popup.js*.

That could become important if, for example:

1. user displays the popup while in landscape mode, and  popup size reduced to fit in viewport.
2. users closes the popup
3. user rotates phone to portrait mode
4. user reopens the popup

In step 4, the popup should be taller than it was at the end of step 1.   Maybe it will still be shrunk, or maybe it doesn't need to be shrunk.

Note that there is code already so that on every iteration `_naturalHeight` is supposed to be set to the height the popup would have been had it not been shrunk:

```js
wrapper.style.height = "auto";
...
args._naturalHeight = widget.offsetHeight;
```

I don't know why it's not working.

**Comment by lbod** [comment]
> In step 4, the popup should be taller than it was at the end of step 1. Maybe it will still be shrunk, or maybe it doesn't need to be shrunk.

So that's handled by `_size` i.e. `Viewport.on("resize", this._repositionAll.bind(this));` 

I do understand what you're saying re: 
> it needs to compare the viewport's current height to the height the popup *would have been if it hadn't been shrunk by popup.js.*

But the `resize` handler is taking care of that. ISTM you either want the code redesigned so that `args._naturalHeight` is instead set to the `scrollHeight`? 

Or, possibly `_naturalHeight` should just be renamed to `_visibleHeight`?

---


> Note that there is code already so that on every iteration _naturalHeight is supposed to be set to the height the popup would have been had it not been shrunk:

> ```
> wrapper.style.height = "auto";
> ...
> args._naturalHeight = widget.offsetHeight;

> ```
> I don't know why it's not working.

This is the part that is confusing me, the fact there's a wrapper around the widget; but the fact the code is using `offSetHeight` to determine the size means that size calculations will only ever be concerned with the visible height, not the actual height without the viewport size restriction.
 
You should hopefully know seeing as you wrote this but with how the current code is designed, my minor change does make it work correctly.

**Comment by wkeese** [comment]
> But the resize handler is taking care of that. 

That's incorrect, because the resize handler doesn't affect hidden popups; it only affects popups that are currently shown.

> Reduce the height of your dev tools (increase the viewport height,

I assume step 5 should say "Increase" not "Reduce".

> So we should be using scrollHeight to calculate _naturalHeight rather than the offSetHeight

The problem with using scrollHeight is that it isn't what we want if the application has limited the popup's height.  offsetHeight is what we want, but you first need to roll back any size changes made by the popup code itself.    There's already code for that, so I don't know why it's not working.

**Comment by wkeese** [comment]
PS: I looked at this some more, and have two comments:

1. The popup.js code sets the height of the wrapper `<div>` rather than the height of popup widget itself, and expects the popup widget to resize accordingly.   But, popup.js also has some workaround code for old Android where it sets the height of the popup widget itself, and I'm not sure that setting is being rolled back when the popup is hidden / reshown.

2. You mentioned using `scrollHeight` rather than `offsetHeight` to get the natural height of the widget.  It's a good idea, but I don't think it will work in certain cases.   For example, if the app defines the popup widget as something like:

```html
<div style="height: 100px">
   ... lots and lots of text ...
</div>
```

In this case, the `scrollHeight` will be a large number, but really the application has constrained the widget height to 100px, so the "natural height" is 100px and the popup.js code shouldn't try to further constrain the height.

Also, in a more complex case like:

```html
  <d-linear-layout vertical="true">
    <div style="height: 20%">Top (20%)</div>
    <div class="fill">Center (Fill) ... lots of text ...</div>
    <div style="height: 50px">Bottom (50px)</div>
  </d-linear-layout>
```

If the `<d-linear-layout>` is somehow constrained so that the `<div class="fill">` gets a scroll bar, then `scrollHeight` (of the `<d-linear-layout>`) will not tell us the natural height.   AFAIK the only way to get the natural height is to move the widget offscreen (like moveOffScreen() does), and remove any height settings on the wrapper.

Hope that makes sense.

**Comment by wkeese** [comment]
There's a lot written here, but the specific issue originally reported in this ticket now works.  It's been working since ee21727aaf22a673cee6f74276c5a5140d112bbf.
