### ISSUE TITLE
delite/KeyNav: listen click instead pointerdown and avoid double navigation

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/delite#374]
Since 7d19b8992684e0d8acf54fbcd93af572ca8fc895, KeyNav triggers navigation on "pointerdown" and, if focusDescendants=true, also on "focusin". Two questions/issues:

* Shouldn't it listen to "click" rather than "pointerdown"?
* Is it intentional that both handlers are called when focusDescendants=true, leading to two calls of `_descendantNavigateHandler()` when clicking a navigateable item?

How to reproduce:
Load https://github.com/ibm-js/delite/blob/master/tests/functional/KeyNavTests.html and click for instance the first "Apple" element in the page while monitoring the calls of the "pointerdown" and "focusin" handlers of KeyNav (say, using console.log or breakpoints).
=> The navigation occurrs on mouse down, while it might be better that it occurs on mouse up.
=> Both handlers are called, and both handlers call the `_descendantNavigateHandler()` method.

**Comment by wkeese** [comment]
> Shouldn't it listen to "click" rather than "pointerdown"?

Well, navigation typically happens on mousedown.  For example, IIRC if you click an `<input>` then it gets focused on mousedown rather than mouseup.   So even on non-focusable nodes I think it makes sense to be consistent.

> Is it intentional that both handlers are called when focusDescendants=true, leading to two calls of _descendantNavigateHandler() when clicking a navigateable item?

I wouldn't say that it's "intentional", but it is expected, and that's why the code in KeyNav#_descendantNavigateHandler() is wrapped in :

```js
if (child && child !== this.navigatedDescendant)
```

I suppose the if() check code be moved to the three places that call `_descendantNavigateHandler()`.  
What issue you are trying to solve?

**Comment by AdrianVasiliu** [comment]
> Well, navigation typically happens on mousedown

Well, might depend on what kind of navigation we are talking. If it's about a HTML link, the browsers navigates at mouse up, not down. Judging after how I feel it when playing with your KeyNavTests.html, the current way seems to forbid changing your mind - once the mouse is down, you can't give up by keeping the mouse down and moving it away.

> IIRC if you click an `<input>` then it gets focused on mousedown rather than mouseup. 

But KeyNav has the "focus-less" mode... (which is the one I use for Combobox). I wonder whether it must be on "down", not "up" even if no focus is envolved.

> What issue you are trying to solve?

The one mentioned in https://github.com/ibm-js/deliteful/pull/497#issuecomment-72015834.

**Comment by AdrianVasiliu** [comment]
If it wouldn't be nonsense, maybe it could be oferred as an option (via a flag)? Unless you'd want to rely on the existing focusDescendants, and go with "click" instead "pointerdown" when this flag is false.

**Comment by wkeese** [comment]
> Well, might depend on what kind of navigation we are talking. If it's about a HTML link, the browsers navigates at mouse up, not down.

I'm using "navigation" as KeyNav does, to mean either "focus" or the appearance of being focused even though technically focusDescendants == false.

> I wonder whether it must be on "down", not "up" even if no focus is envolved.

The idea is to be consistent in behavior regardless of implementation details such as whether the nodes are actually getting focus or just appear to be getting focus.

> The one mentioned in ibm-js/deliteful#497 (comment).

Apparently your issue is whether items get selected on mousedown or mouseup.   But selection is different than navigation. Assuming selection used to work on mouseup before your PR, then I'd say to just keep doing mouse support the old way.   In other words, don't close the dropdown based on "keynav-child-navigated", but rather inside your `this.list.observe(...)` code block.

**Comment by AdrianVasiliu** [comment]
> Assuming selection used to work on mouseup before your PR,

Yes, this is the case. 

> then I'd say to just keep doing mouse support the old way.   In other words, don't close the dropdown based on "keynav-child-navigated", but rather inside your `this.list.observe(...)` code block.

Basing it on "keynav-child-navigated" was the false good idea for having a common handling for mouse and keyboard interaction, since in both cases navigation events are fired by KeyNav/List. Now, if I have to live with KeyNav firing navigation events on pointerdown, yes, I have to find a different way. 

You refer to `this.list.observe(...)`, but I can't observe the changes of selectedItem(s) property, because List does not change the selection while the user navigates with the keyboard. I could instead observe the changes of the navigatedDescendant property, but this wouldn't fire on mouse up either, since it happens together with the navigation event (thus on pointerdown), isn't it?

**Comment by AdrianVasiliu** [comment]
Thus, unless you have a better idea, the only thing I can see is to give up on having a common handling for both mouse and keyboard, and use a this.list.on("click") for mouse and the navigation events only for keyboard interaction.

**Comment by AdrianVasiliu** [comment]
> the only thing I can see is to give up on having a common handling for both mouse and keyboard, and use a this.list.on("click", ...) for mouse and the navigation events only for keyboard interaction.

This seems to work so far. I'm cleaning it and doing more tests, then I'll update the PR accordingly.

**Comment by wkeese** [comment]
Yes, that makes sense to me.   I suppose the click handling code should also execute when the user presses the enter key.

**Comment by AdrianVasiliu** [comment]
This worked. I'm closing my issue.
