### ISSUE TITLE
Change widget template dynamically

### ISSUE THREAD

**Issue by EAlexRojas** [ibm-js/delite#414]
Sometimes it could be useful to change the template used to render a widget depending on the context it's used or depending on the user's needs.

As an example, I'm working on an Accordion widget, which have panels as children. Normally, a panel has a TitleBar and a content, but when it's used into an Accordion it should be render with a ToggleButton instead of a simple TitleBar. 

I think it could be achieved by adding a method on `Widget` that updates the `template` property an re-renders the widget; Taking into account that it should be needed to undoing the changes introduced by the default template on the original markup.
In the case of a `Container`, it may be needed to place the children of the containerNode back to its original place before re-rendering. (if the containerNode is not the main node of the widget)

What do you think about it?

**Comment by wkeese** [comment]
It's an interesting idea, but it seems quite complicated to implement, and without a lot of return.

The Accordion example you mentioned could alternately be solved by having a special AccordionPanel widget that extends the generic Panel widget, and the app would use AccordionPanel inside of an Accordion.

Another use case would be to switch the template based on the form factor (like phone vs. tablet vs. desktop).  I can see the value in that.  Maybe it's something that could be done in the future.

**Comment by cjolif** [comment]
> It's an interesting idea, but it seems quite complicated to implement, and without a lot of return.

I think @EAlexRojas has a prototype working. But maybe it is far from being final. Maybe @EAlexRojas you could share the commit ID where you have this working?

> The Accordion example you mentioned could alternately be solved by having a special AccordionPanel widget that extends the generic Panel widget, and the app would use AccordionPanel inside of an Accordion.

I guess the idea is for our users to not have to bother about that. They do use the same panel and when used in the accordion the accordion subsitute the template.

**Comment by EAlexRojas** [comment]
You can see the prototype I have on this commit: https://github.com/EAlexRojas/delite/commit/6a731e00239b1431816eeb1d5ba6452055bb39b3 . 
As @cjolif mentioned, it could be far from being final. 
I tested it with some `Widget`,`Container` and my implementation of the Accordion and it works fine, but maybe I didn't take into account all the cases ?
I let you take a look at it.

**Comment by wkeese** [comment]
Thanks for the link.  That is interesting.  I thought there would be more to it, but maybe that's all you need.   One thing is that instead of having a `changeTemplate()` method you should probably have a `_setTemplateAttr()` method, so that apps/widgets can simply set `this.template = ...`.

**Comment by wkeese** [comment]
Another question: should `preRender()`, `postRender()`, and `attachedCallback()` also be re-run when the template is changed (assuming the template is changed after they are called the first time)?

For deliteful/Checkbox, `postRender()` needs to be re-run, to recreate the event handlers on `this.focusNode`:

```js
postRender: function () {
	this._lbl4 = null;
	this.on("click", this._inputClickHandler.bind(this), this.focusNode);
	this.on("change", this._inputClickHandler.bind(this), this.focusNode);
},
```

(As a side note, it would have been better to set up those event handlers in the template, via `attach-event`.)

On the other hand, it would be detrimental to rerun `Slider#postRender()`, because that would set up duplicate event handlers on the widget's root node:

```js
postRender: function () {
	...
	this.on("pointerdown", this.pointerDownHandler.bind(this));
	this.on("pointermove", this.pointerMoveHandler.bind(this));
	this.on("lostpointercapture", this.lostCaptureHandler.bind(this));
	this.on("keydown", this.keyDownHandler.bind(this));
	this.on("keyup", this.keyUpHandler.bind(this));
},
```

Remember that the widget's root node is not replaced by the template, so the listeners set up on widget creation will continue to exist even if the template is replaced.

Probably `preRender()` and `postRender()` should always be called along with `render()`, just because of the way the functions are named, but we would need to clearly document this more complicated lifecycle.  Or alternately, rename those methods to something like `atStartOfCreation()` and `atEndOfCreation()`... or have those new methods in addition to the existing methods.

In any case, existing widgets would need to be refactored to move one-time-only code (such as the Slider example above) into methods(s) that only get called on widget creation.

**Comment by wkeese** [comment]
I'm going to start working on this, with the following plan:

1. Widgets will be initially rendered (ie `preRender()`, `render()`, and `postRender()`) on the first call to `Widget#refreshRendering()`.  (Previously they were rendered synchronously, when `createdCallback()` called `render()`.)
2. Whenever the `template` variable is changed, `Widget#refreshRendering()` will call some teardown method (`unrender()`?) to erase events and attach points from the previous rendering.   Then it will rerender the widget, by calling `preRender()`, `render()`, and `postRender()`.
3. As in your prototype, `Container` will save and restore the child nodes.

This means that widgest may need to be modified as follows, especially for them to continue working when/if their template is set or changed dynamically:

1. Code that should only run once should be moved from `preRender()` and/or `postRender()` to `createdCallback()`.
2. Widgets often have code like `this.notifyCurrentValue("value", "max");` in `postRender()` which really means that after the widget is rendered, run the code in `refreshRendering()` for `value` and `max` even if those properties are still the default value.   In other words, that code is necessary as part of the rendering.  Probably those notifyCurrentValue() calls should be removed and instead `refreshRendering()` should be changed so that `if ("value" in props || "max" in props)` is replaced by something that also triggers when the widget is [re]rendered, for example `if ("value" in props || "max" in props || "renderCount" in props)`.  TODO: figure out details.
3. `createdCallback()` and even `attachedCallback()` will execute and complete before the initial rendering.  They should not assume the widget has been rendered.
4. Code to set the template dynamically (based on user specified properties) should go in `computeProperties()`.   The code should simply set the `this.template` property, and that will trigger `refreshRendering()` to rerender the template.
5. Note that due to chaining, `Widget#refreshRendering()` always runs before the `refreshRendering()` methods in subclasses.  So, subclasses' `refreshRendering()` methods can still assume that attach points etc. are set up.
6. In the future, it may make sense to get rid of the `preRender()`, `render()`, and `postRender()` methods altogether.

**Comment by cjolif** [comment]
@wkeese do you plan to modify the deliteful widget accordingly? If not and as I suspect we won't have time ourselves for a while, then I think it might be good, to get some new version of delite be tagged before this work is merged so that we can have a version of delite we can work with.

**Comment by wkeese** [comment]
I don't have any plans to update deliteful, so sure, I'll tag a delite 0.8 before merging this into master.

**Comment by asudoh** [comment]
I heard better context from @wkeese of this issue, which made me wonder why don’t we implement conditional template like [`<template if=“{{condition}}">`](http://ibm-js.github.io/liaison/docs/0.1.6/template.html) as part of our template engine, or creating a custom element for that purpose (say, `d-if`) like [this one](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if)?

**Comment by wkeese** [comment]
As I mentioned privately to @asudoh, and vaguely mentioned in #420, the essence of this refactor is for `render()` etc. to be called after the user specified properties are processed.  That's probably a good change, even without any added functionality, because it can make `render()` more efficient.  With the current code, sometimes `render()` generates some DOM and then `refreshRendering()` changes it on the next clock tick, which is inefficient.  A simple example:

```js
register(...  {
    hide: false,
   render: function () {
      this.innerHTML = "hello world";
   },
   refreshRendering: function (props) {
        if("hide" in props) {
            this.style.display = this.hide ? "none" : "";
        }
   }
}
```

Given markup like `<my-widget hide=true></my-widget>`, it will render "hello world" to the screen and then on the next microtask (after the text has rendered), hide it.

----

I agree that conditional templates would be useful for the Accordion case mentioned above.  The reason we don't/didn't implement them is because we agreed that advanced template features (like `if` and loops) would be left to liaison.

I spent some time today thinking about implementing conditionals in delite/handlebars! but I think it would be very hard with the current architecture.

Perhaps long term, delite/handlebars should be rearchitected to work like liaison, or [some] of the liaison code should be moved into delite, but that seems like a much bigger project than just allowing the template to be changed dynamically.
