### ISSUE TITLE
To dynamically specifying a template upon instantiation of a widget

### ISSUE THREAD

**Issue by martinfitzg** [ibm-js/delite#416]
Hello all,
             Don't really think this qualifies as an issue, but I'm having this problem any help would be appreciated......   I need to be able to specify a template externally as a parameter to a widget when it is instantiated.  In the life cycle of the Widget, the mixin phase happens after the Render function so this rules this out.  Then trying to extend the widget something like the like this

_buildWidget: function(templateInput){

        var AlteredWidget = dcl([MyWidget], {				
				render : function () {
                                          this.template =templateInput;
					if (this.template) {
				            this._templateHandle = this.template(this.ownerDocument, register);
			                 }
				}});
    return AlteredWidget;
}

But when this is done, the "new" Render function never gets called.  

Any advice is appreciated........

**Comment by cjolif** [comment]
Isn't it related to #414?

**Comment by martinfitzg** [comment]
Hey Christophe, I taught that two initially, but to me #414 would seem to want to be able to change the template of a widget during "run time" not at the initial instantiation of a widget.  I'm open to correction.....

**Comment by wkeese** [comment]
I think this is the same as #414, because initial parameters are handled in the same way as properties changed during "run time".   (They are handled in `computeProperties()` or `refreshRendering()`.)  So, setting the template like:

```js
new MyWidget({ template: ... })
```

is no different than setting the template like:

```js
var x = new MyWidget();
x.template = ...;
```

or even:

```js
var x = new MyWidget();
setTimeout(function () { x.template = ...; }, 100);
```

Also, "setting" the template and "changing" the template are essentially the same thing.  The only difference is whether the template was initially set, or whether it was null.   In the examples above, the widget prototype presumably doesn't specify a template, so there's no template until the application specifies one.

**Comment by martinfitzg** [comment]
I stand corrected!
