### ISSUE TITLE
Centered dropdown fails to render correctly on IE11

### ISSUE THREAD

**Issue by cf-demo-app** [ibm-js/delite#422]
Simple example:

           require(["deliteful/Store", "deliteful/list/List",
                "deliteful/Combobox", "requirejs-domready/domReady!"],
             function () {   
               document.body.style.display = "";
               var combobox = document.getElementById("combo");
               combobox.dropDownPosition = ["center"];            
             });
          });

Runnable at http://jsfiddle.net/50qrd36f/

On IE11, when centered, the popup widget has effectively zero width.

**Comment by cf-demo-app** [comment]
Hi folks, has there been an opportunity to look at this? Thanks again.

**Comment by martinfitzg** [comment]
Another example of it not working  http://jsfiddle.net/y9urjku9/1/

**Comment by wkeese** [comment]
OK thanks, the code in the first fiddle doesn't work in 0.8.0 because `<d-store>` no longer exists, but I reproduce the failure using the second fiddle.

Of course, since we are testing on desktop, the dropdown isn't supposed to be centered.  The problem is merely with the width.

**Comment by wkeese** [comment]
This is arguably an issue with `<d-list>`, not with delite/popup or delite/HasDropDown.

The `<d-list>` dropdown's `offsetWidth` is reported as 16px when it should be around 170px.   I think this is because `<d-list>` is `display: flex` inside of a `position: absolute` `<div>`, and that doesn't work right on IE11.

I'm not surprised this is broken.  Usually the application specifies a flex container's width -- often the width of the viewport itself -- but in this case we are essentially asking the container to compute how much width it needs.   It works with `<div style="position: absolute">hello world</div>` but apparently not in this more complicated case.

A crappy workaround is to do:

	.d-combobox-list {
		min-width: 15em;
	}

where the `15em` number is adjusted to match your longest label in a dropdown menu.  That can run into problems in the long run, for example if the user has a custom stylesheet that increases the font-size, or is running the machine in high contrast (large text) mode, or if the app is translated to German and all the labels get longer.

**Comment by wkeese** [comment]
Test file showing IE11 problem (or limitation).
[flex.html.txt](https://github.com/ibm-js/delite/files/118895/flex.html.txt)

**Comment by wkeese** [comment]
Replaced by ibm-js/deliteful#590.
