### ISSUE TITLE
No way to prevent XML escaping of expressions in the handlebar templates

### ISSUE THREAD

**Issue by wardkj** [ibm-js/delite#427]
When we pass XML safe content in for our labels, it gets escaped when added to the page.

Is there a way to tell the template handler to not escape certain values.

e.g. We want label to appear like the 2nd image
![image](https://cloud.githubusercontent.com/assets/2191715/9810446/d0f01f22-5868-11e5-970d-4dce176cdc44.png)

![image](https://cloud.githubusercontent.com/assets/2191715/9810471/f8bbe0d6-5868-11e5-959d-013014440485.png)

**Comment by wkeese** [comment]
That's right, there's no way to tell the template code to treat a value as HTML rather than text, and that can't really be changed.

But in your example, you should just convert your label into a normal text string, by something like `$('<textarea>').html(label).text()`, see http://stackoverflow.com/questions/5796718/html-entity-decode.  Could do it inside or outside your widget.
