### ISSUE TITLE
Handlebars parser is not handling JSON data correctly

### ISSUE THREAD

**Issue by wardkj** [ibm-js/delite#428]
Hi,

the hanlebars parser doesn't like JSON that ends in two braces.

If, say, we pass in a template like 

`<template requires=""><button someAttr="{&quot;one&quot;: &quot;value&quot;,&quot;two&quot;: {&quot;inner&quot;: &quot;value&quot;}}"></button></template>`

once its parsed, the final }} are missing from the attribute value

![image](https://cloud.githubusercontent.com/assets/2191715/9878495/ef15710a-5bba-11e5-8e2d-29a21991fffc.png)

**Comment by wkeese** [comment]
Huh?  The whole point of handlebars is to bind the DOM to properties in the widget, and that's what the `{{ ... }}` syntax is for.   For example, `<button someAttr="{{propertyXYZ}}">`.  You're expecting the `}}` to just be treated as literal text?

**Comment by martinfitzg** [comment]
The use case here is that certain attributes that are in the markup of the template contain json eg 

```
<template>
     <my-custom-component someattr="{name: {first : 'john', last: 'doe'}}"></my-custom-component >
</template>
```

As the markup for this template is been generated server side and the json that is been set here drives some sort of state when the widget initializes.  

The problem here is the last part of the json ....  'doe'}} .... as there is 2 curly closing brackets together. This causes issue with handlebars 'compiling', as it's not valid as far as it is concerned, as there is no way to tell handlebars that it should be ignored.  

Is there any way that it can be told to ignore this block of json during it's 'compile' phase ?

**Comment by wkeese** [comment]
Hmm, there's no way to do that currently.  I suppose the `toJs()` method in handlebars.js should be modified to be less fragile, and ignore the case above since there's no opening `{{` characters.  You've shown an example where JSON contains `}}` but I suppose there's never a case in JSON where there's a `{{`?

**Comment by wkeese** [comment]
PS: You're walking on thin ice though, because if you are inserting arbitrary data into the template then theoretically the strings literals themselves could contain curly brackets:

```xml
<template>
     <my-custom-component someattr="{name: '{{weird name}}'}"></my-custom-component >
</template>
```

At that point I guess you would need to start escaping strings on the server, converting curly braces to `&#123;` and `&#124;`.    Actually you should probably be escaping already in case your user text contains an `&` character.
