### ISSUE TITLE
Arrow key navigation broken in Firefox

### ISSUE THREAD

**Issue by kgibb** [ibm-js/delite#433]
KeyNav no longer works with Firefox. The KeyboardEvent.key value returned for the left arrow key is "ArrowLeft", not "Left".

Tested with FF 42.0

**Comment by wkeese** [comment]
Hmm, you are right.  Also, presumably key navigation in deliteful's Slider and and StarRating widgets are broken.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key and https://w3c.github.io/uievents/#fixed-virtual-key-codes list "ArrowLeft" as the new normal.  It used to be "Left" (and "Right" and "Up" and "Down"), and that's how it still comes out on Chrome and Microsoft Edge.

So, the issue is in the `delite/on` normalization code.  I could temporarily map "ArrowLeft" to "Left", for backwards compatibility, but eventually it's better for `delite/on` to map "Left" to "ArrowLeft", to match the standard, and then update client code (delite/KeyNav, deliteful/Slider, deliteful/StarRating, etc.) to use the standard names.

**Comment by clmath** [comment]
Shouldn't that be in 0.8.1 ?

**Comment by wkeese** [comment]
Yes, it's in 0.8.1, but there's no milestone setting for 0.8.1.  Does it matter?
