### ISSUE TITLE
how to build with require.js builder ?

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/delite#457]
Hi,
I am currently using the official grunt plugin(grunt-contrib-requirejs) for building require.js applications which works just fine. 

The build stops on delite/register because "document is undefined". 

I am wondering now delite/deliteful is r.js compatible or not. I saw you have own grunt tasks but those are not suited to build my application.

is there a trick or are your build tools locked in ? 

thanks a lot.
g

**Comment by gbaumgart** [comment]
i got over the document error by using the r.js "mainConfigFile" option:

```
requirejs.config({
    config: {
        "requirejs-dplugins/has": {
            builder: true
        }
    }
});
```

but then I get 'require.getNodePath is not a function'. I found https://github.com/ibm-js/grunt-amd-build/blob/master/tasks/lib/requirejs.js which defines that but at the end it means that official r.js tools are not working for delite.

**Comment by gbaumgart** [comment]
so after defining requirejs.getNodePath in grunt-contrib-requirejs, i get "Cannot read property 'id' which came from define('module',....) to feed : 

require.nodeRequire(require.getNodePath(require.toUrl(module.id).replace(/[^\/]*$/,
		"node_modules/jsdom")),module).jsdom("") : document;

it seems that this is resolved in your own grunt-amd-plugin. Can someone confirm that delite/deliteful can be only build with ibm-js/grunt-amd-plugin ? The problem with that plugin is that it seems a little monolith and even dangerous (lost my whole source directory once).

**Comment by gbaumgart** [comment]
Or is there another way to use deliteful in ordinary require.js projects? Possibly I use the  grunt-amd-plugin just for precompiling delite layers and then included them in my r.js app builds(grunt-contrib-requirejs), that would do too. Otherwise, i don't know else except dropping delite entirely or fixing it (seems  bigger task since you introduced everywhere dependencies to your own build chain).

**Comment by gbaumgart** [comment]
ok, at the end i got it sorted through your grunt-amd-plugin but i can tell you, it's a real PITA. in the end your libraries are not really require.js compatible when you dictate the whole build process. 

and the trouble is actually about 2-3 other very weird/odd design decisions you have done and locking in your build chain for no reasons: 

delite/theme (breaks r.js builds)
delite/handlebars (breaks r.js builds)
requirejs-dplugins/css (breaks r.js builds)

all that resources are loaded usually somewhere else, making it also difficult to switch themes or templates.

anyways, looks i gonna drop delite now too. so, no more bothering from my side but i can tell you: another huge amount of time wasted with dojo libraries.

**Comment by wkeese** [comment]
You alluded to "2-3 other very weird/odd design decisions".  I'm interested to know what they are.

Note that I actually removed delite's `require.getNodePath()` calls recently in d03a17176363a7793b5646a1b519c8f9914d0df8.  So r.js should be able to handle those files assuming that you first `npm install jsdom` into the directory running r.js.   Is requirejs-dplugins/css just the same basic problem, with the load of `clean-css`?

I too wanted the ibm-js code to be built with r.js.  But allegedly it's impossible to get r.js to support stuff we wanted like language bundles with rollup (for example, a layer file for UK English containing nls/en-gb/messages.js, nls/en/messages.js and nls/messages.js).   But I can't speak authoritatively since I wasn't involved in that part of the project.

**Comment by wkeese** [comment]
PS: Oh also, where in delite/register is `document` undefined, and why is it only a problem with r.js, but not our own builder?   The code is designed to only reference `document` when run from a browser.

**Comment by gbaumgart** [comment]
thanks Bill,
was not meant to offend. And as always I am very thankful for your insights.
After fighting a day more with the build tools, I am actually happy now. I first thought that were bugs in the code but I understand the need for r.js plugins, done as grunt plugin = which is fine, after all.

**Comment by gbaumgart** [comment]
document:  its in delite/theme i think

**Comment by wkeese** [comment]
I understand, but I want to know exactly what to change so that the ibm-js code builds under r.js, without adding that config you mentioned:

```
requirejs.config({
    config: {
        "requirejs-dplugins/has": {
            builder: true
        }
    }
});
```

IIUC, your `requirejs.config(...)` workaround is suboptimal because all the code inside the `if (has("builder") { ... }` blocks will end up in the layer file(s), and then it gets downloaded to the browser.   And that's a waste of bandwith.
